export const exams = [
  'GATE',
  'JEE',
  'NEET',
  'UPSC',
  'SSC',
  'Banking',
  'Railway',
]

export const features = [
  {
    title: 'Adaptive Practice',
    text: 'Switch between school, college, and competitive MCQs with instant explanations.',
  },
  {
    title: 'Timed Mock Tests',
    text: 'Simulate real exam pressure with configurable timers and performance reports.',
  },
  {
    title: 'Progress Analytics',
    text: 'Track accuracy, weak topics, and growth with a beautiful student dashboard.',
  },
]

export const stats = [
  { value: '10K+', label: 'Questions' },
  { value: '95%', label: 'Accuracy Boost' },
  { value: '24/7', label: 'Practice Access' },
]

export const practiceQuestions = [
  {
    id: 1,
    topic: 'Physics',
    exam: 'JEE',
    question: 'What is the SI unit of electric current?',
    options: ['Ampere', 'Volt', 'Watt', 'Ohm'],
    answer: 'Ampere',
    explanation: 'The SI unit of electric current is the ampere.',
  },
  {
    id: 2,
    topic: 'Chemistry',
    exam: 'NEET',
    question: 'Which gas is most abundant in Earth’s atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    answer: 'Nitrogen',
    explanation: 'Nitrogen makes up about 78% of Earth’s atmosphere.',
  },
  {
    id: 3,
    topic: 'Maths',
    exam: 'JEE',
    question: 'What is 12 × 8?',
    options: ['88', '90', '96', '100'],
    answer: '96',
    explanation: '12 multiplied by 8 equals 96.',
  },
  {
    id: 4,
    topic: 'Biology',
    exam: 'NEET',
    question: 'Which organelle is the powerhouse of the cell?',
    options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi apparatus'],
    answer: 'Mitochondria',
    explanation: 'Mitochondria produce ATP which powers cellular processes.',
  },
  {
    id: 5,
    topic: 'Physics',
    exam: 'JEE',
    question: 'What is the acceleration due to gravity (approx) on Earth?',
    options: ['9.8 m/s^2', '10.8 m/s^2', '8.9 m/s^2', '12 m/s^2'],
    answer: '9.8 m/s^2',
    explanation: 'Standard gravity is approximately 9.8 m/s^2.',
  },
  {
    id: 6,
    topic: 'Signals',
    exam: 'GATE',
    question: 'What is the unit of frequency?',
    options: ['Hertz', 'Newton', 'Joule', 'Pascal'],
    answer: 'Hertz',
    explanation: 'Frequency is measured in Hertz (cycles per second).',
  },
  {
    id: 7,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Who is the head of the State in India?',
    options: ['President', 'Prime Minister', 'Chief Justice', 'Governor'],
    answer: 'President',
    explanation: 'The President is the constitutional head of the State in India.',
  },
  {
    id: 8,
    topic: 'Quantitative Aptitude',
    exam: 'Banking',
    question: 'If 5x = 20, what is x?',
    options: ['2', '3', '4', '5'],
    answer: '4',
    explanation: '5x = 20 implies x = 4.',
  },
  {
    id: 9,
    topic: 'General Science',
    exam: 'SSC',
    question: 'Water boils at what temperature at sea level?',
    options: ['100°C', '90°C', '80°C', '120°C'],
    answer: '100°C',
    explanation: 'At standard atmospheric pressure, water boils at 100°C.',
  },
  {
    id: 10,
    topic: 'General Knowledge',
    exam: 'Railway',
    question: 'What does IRCTC primarily provide?',
    options: ['Train ticket bookings', 'Bank loans', 'Health insurance', 'University admissions'],
    answer: 'Train ticket bookings',
    explanation: 'IRCTC provides online train ticketing and related services.',
  },
  {
    id: 11,
    topic: 'Biology',
    exam: 'NEET',
    question: 'Which blood cells help in clotting?',
    options: ['Platelets', 'RBCs', 'WBCs', 'Plasma'],
    answer: 'Platelets',
    explanation: 'Platelets (thrombocytes) play a key role in blood clotting.',
  },
  {
    id: 12,
    topic: 'Chemistry',
    exam: 'GATE',
    question: 'pH of a neutral solution at 25°C is?',
    options: ['7', '1', '14', '0'],
    answer: '7',
    explanation: 'At 25°C, neutral water has pH 7.',
  },
  {
    id: 13,
    topic: 'Current Affairs',
    exam: 'UPSC',
    question: 'Which body publishes the Economic Survey of India?',
    options: ['Ministry of Finance', 'NITI Aayog', 'RBI', 'Parliament'],
    answer: 'Ministry of Finance',
    explanation: 'The Economic Survey is prepared by the Ministry of Finance.',
  },
  {
    id: 14,
    topic: 'Reasoning',
    exam: 'SSC',
    question: 'Find the next number in series: 2, 4, 6, 8, ?',
    options: ['10', '9', '12', '11'],
    answer: '10',
    explanation: 'Sequence increases by 2 each time, next is 10.',
  },
  {
    id: 15,
    topic: 'General Awareness',
    exam: 'Banking',
    question: 'Which is the central bank of India?',
    options: ['RBI', 'SBI', 'ICICI', 'PNB'],
    answer: 'RBI',
    explanation: 'Reserve Bank of India (RBI) is the central bank.',
  },

  // --- UPSC ---
  {
    id: 16,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Who is the current President of India?',
    options: ['Droupadi Murmu', 'Ram Nath Kovind', 'Pratibha Patil', 'C.P. Radhakrishnan'],
    answer: 'Droupadi Murmu',
    explanation: 'Droupadi Murmu has been serving as the President of India since 2022.',
  },
  {
    id: 17,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Who is the current Vice President of India?',
    options: ['C.P. Radhakrishnan', 'Jagdeep Dhankhar', 'Venkaiah Naidu', 'Hamid Ansari'],
    answer: 'C.P. Radhakrishnan',
    explanation: 'C.P. Radhakrishnan is the 15th Vice President of India.',
  },
  {
    id: 18,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Who is the current Chief Justice of India?',
    options: ['Justice Surya Kant', 'Justice D.Y. Chandrachud', 'Justice N.V. Ramana', 'Justice U.U. Lalit'],
    answer: 'Justice Surya Kant',
    explanation: 'Justice Surya Kant is the 53rd Chief Justice of India.',
  },
  {
    id: 19,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Fundamental Rights are enshrined in which Part of the Indian Constitution?',
    options: ['Part III', 'Part IV', 'Part V', 'Part II'],
    answer: 'Part III',
    explanation: 'Part III of the Constitution (Articles 12-35) deals with Fundamental Rights.',
  },
  {
    id: 20,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Which Article of the Constitution is known as the "Right to Constitutional Remedies"?',
    options: ['Article 32', 'Article 21', 'Article 19', 'Article 14'],
    answer: 'Article 32',
    explanation: 'Dr. Ambedkar called Article 32 the "heart and soul" of the Constitution.',
  },
  {
    id: 21,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Which constitutional amendment added the words "Socialist" and "Secular" to the Preamble?',
    options: ['42nd Amendment', '44th Amendment', '52nd Amendment', '61st Amendment'],
    answer: '42nd Amendment',
    explanation: 'The 42nd Amendment Act (1976) added "Socialist", "Secular", and "Integrity" to the Preamble.',
  },
  {
    id: 22,
    topic: 'History',
    exam: 'UPSC',
    question: 'Who was the Chairman of the Drafting Committee of the Indian Constitution?',
    options: ['Dr. B.R. Ambedkar', 'Jawaharlal Nehru', 'Rajendra Prasad', 'Sardar Patel'],
    answer: 'Dr. B.R. Ambedkar',
    explanation: 'Dr. B.R. Ambedkar chaired the Drafting Committee of the Constituent Assembly.',
  },
  {
    id: 23,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'The anti-defection law is covered under which schedule of the Constitution?',
    options: ['Tenth Schedule', 'Ninth Schedule', 'Eighth Schedule', 'Seventh Schedule'],
    answer: 'Tenth Schedule',
    explanation: 'The Tenth Schedule, added by the 52nd Amendment (1985), deals with disqualification on grounds of defection.',
  },
  {
    id: 24,
    topic: 'History',
    exam: 'UPSC',
    question: 'In which year was the Quit India Movement launched?',
    options: ['1942', '1930', '1920', '1947'],
    answer: '1942',
    explanation: 'The Quit India Movement was launched by Gandhi on 8 August 1942.',
  },
  {
    id: 25,
    topic: 'History',
    exam: 'UPSC',
    question: 'Who founded the Indian National Congress in 1885?',
    options: ['A.O. Hume', 'Bal Gangadhar Tilak', 'Mahatma Gandhi', 'Dadabhai Naoroji'],
    answer: 'A.O. Hume',
    explanation: 'Allan Octavian Hume, a retired British civil servant, founded the INC in 1885.',
  },
  {
    id: 26,
    topic: 'History',
    exam: 'UPSC',
    question: 'In which year was the Battle of Plassey fought?',
    options: ['1757', '1764', '1857', '1600'],
    answer: '1757',
    explanation: 'The Battle of Plassey (1757) marked the beginning of British political power in India.',
  },
  {
    id: 27,
    topic: 'Geography',
    exam: 'UPSC',
    question: 'Which is the longest river in India?',
    options: ['Ganga', 'Godavari', 'Yamuna', 'Brahmaputra'],
    answer: 'Ganga',
    explanation: 'The Ganga is the longest river flowing entirely within India.',
  },
  {
    id: 28,
    topic: 'Geography',
    exam: 'UPSC',
    question: 'Which Indian state has the longest coastline?',
    options: ['Gujarat', 'Tamil Nadu', 'Andhra Pradesh', 'Maharashtra'],
    answer: 'Gujarat',
    explanation: 'Gujarat has the longest coastline among Indian states, over 1,600 km.',
  },
  {
    id: 29,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Who is the current Speaker of the Lok Sabha?',
    options: ['Om Birla', 'Meira Kumar', 'Sumitra Mahajan', 'Balram Jakhar'],
    answer: 'Om Birla',
    explanation: 'Om Birla continues as the Speaker of the Lok Sabha.',
  },
  {
    id: 30,
    topic: 'Economy',
    exam: 'UPSC',
    question: 'NITI Aayog replaced which erstwhile body?',
    options: ['Planning Commission', 'Finance Commission', 'National Development Council', 'Election Commission'],
    answer: 'Planning Commission',
    explanation: 'NITI Aayog replaced the Planning Commission in 2015.',
  },
  {
    id: 31,
    topic: 'Current Affairs',
    exam: 'UPSC',
    question: 'Who is the current Chief of the Army Staff of India?',
    options: ['General Upendra Dwivedi', 'General Manoj Pande', 'General Bipin Rawat', 'General M.M. Naravane'],
    answer: 'General Upendra Dwivedi',
    explanation: 'General Upendra Dwivedi is the current Chief of the Army Staff.',
  },
  {
    id: 32,
    topic: 'Economy',
    exam: 'UPSC',
    question: 'In which year was the Goods and Services Tax (GST) implemented in India?',
    options: ['2017', '2014', '2019', '2016'],
    answer: '2017',
    explanation: 'GST was rolled out across India on 1 July 2017.',
  },
  {
    id: 33,
    topic: 'Polity',
    exam: 'UPSC',
    question: 'Which Article empowers the President to declare a National Emergency?',
    options: ['Article 352', 'Article 356', 'Article 360', 'Article 368'],
    answer: 'Article 352',
    explanation: 'Article 352 deals with the proclamation of a National Emergency.',
  },

  // --- SSC ---
  {
    id: 34,
    topic: 'General Knowledge',
    exam: 'SSC',
    question: 'Who is known as the "Missile Man of India"?',
    options: ['Dr. APJ Abdul Kalam', 'Vikram Sarabhai', 'Homi Bhabha', 'C.V. Raman'],
    answer: 'Dr. APJ Abdul Kalam',
    explanation: 'Dr. APJ Abdul Kalam led India’s missile and space programmes.',
  },
  {
    id: 35,
    topic: 'General Knowledge',
    exam: 'SSC',
    question: 'Which Indian city is popularly called the "Silicon Valley of India"?',
    options: ['Bengaluru', 'Hyderabad', 'Pune', 'Chennai'],
    answer: 'Bengaluru',
    explanation: 'Bengaluru hosts India’s largest concentration of IT companies.',
  },
  {
    id: 36,
    topic: 'General Knowledge',
    exam: 'SSC',
    question: 'National Sports Day of India, marking Major Dhyan Chand’s birthday, is celebrated on which date?',
    options: ['29 August', '14 April', '5 September', '2 October'],
    answer: '29 August',
    explanation: 'National Sports Day is observed on 29 August every year.',
  },
  {
    id: 37,
    topic: 'General Knowledge',
    exam: 'SSC',
    question: 'Who composed India’s National Anthem "Jana Gana Mana"?',
    options: ['Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Sarojini Naidu', 'Muhammad Iqbal'],
    answer: 'Rabindranath Tagore',
    explanation: 'Rabindranath Tagore wrote and composed "Jana Gana Mana".',
  },
  {
    id: 38,
    topic: 'Geography',
    exam: 'SSC',
    question: 'Which is the smallest state of India by area?',
    options: ['Goa', 'Sikkim', 'Tripura', 'Nagaland'],
    answer: 'Goa',
    explanation: 'Goa is India’s smallest state by area.',
  },
  {
    id: 39,
    topic: 'Geography',
    exam: 'SSC',
    question: 'The sun rises first in which Indian state?',
    options: ['Arunachal Pradesh', 'Assam', 'Sikkim', 'Manipur'],
    answer: 'Arunachal Pradesh',
    explanation: 'Arunachal Pradesh, in India’s northeast, sees the first sunrise each day.',
  },
  {
    id: 40,
    topic: 'General Knowledge',
    exam: 'SSC',
    question: 'Who was the first woman President of India?',
    options: ['Pratibha Patil', 'Droupadi Murmu', 'Sarojini Naidu', 'Indira Gandhi'],
    answer: 'Pratibha Patil',
    explanation: 'Pratibha Patil served as India’s first woman President from 2007 to 2012.',
  },
  {
    id: 41,
    topic: 'Economy',
    exam: 'SSC',
    question: 'Which Five Year Plan of India focused on rapid industrialization (heavy industries)?',
    options: ['Second Five Year Plan', 'First Five Year Plan', 'Third Five Year Plan', 'Fifth Five Year Plan'],
    answer: 'Second Five Year Plan',
    explanation: 'The Second Five Year Plan (1956-61), based on the Mahalanobis model, emphasized heavy industry.',
  },
  {
    id: 42,
    topic: 'General Knowledge',
    exam: 'SSC',
    question: 'What is the currency of Japan?',
    options: ['Yen', 'Won', 'Yuan', 'Ringgit'],
    answer: 'Yen',
    explanation: 'Japan’s official currency is the Yen.',
  },
  {
    id: 43,
    topic: 'Geography',
    exam: 'SSC',
    question: 'Which is the largest desert in India?',
    options: ['Thar Desert', 'Rann of Kutch', 'Rajasthan Canal Area', 'Sahara'],
    answer: 'Thar Desert',
    explanation: 'The Thar Desert, spread across Rajasthan, is India’s largest desert.',
  },
  {
    id: 44,
    topic: 'Reasoning',
    exam: 'SSC',
    question: 'Find the odd one out: Apple, Mango, Potato, Banana',
    options: ['Potato', 'Apple', 'Mango', 'Banana'],
    answer: 'Potato',
    explanation: 'Potato is a vegetable/tuber; the others are fruits.',
  },
  {
    id: 45,
    topic: 'Reasoning',
    exam: 'SSC',
    question: 'If A=1, B=2, C=3 ... Z=26, what is the sum of the letter values in "CAT"?',
    options: ['24', '20', '26', '22'],
    answer: '24',
    explanation: 'C(3) + A(1) + T(20) = 24.',
  },
  {
    id: 46,
    topic: 'General Science',
    exam: 'SSC',
    question: 'Which gas is commonly used in fire extinguishers?',
    options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    answer: 'Carbon dioxide',
    explanation: 'Carbon dioxide displaces oxygen and smothers fires.',
  },
  {
    id: 47,
    topic: 'General Awareness',
    exam: 'SSC',
    question: 'State Bank of India traces its origins to which bank, established in 1806?',
    options: ['Bank of Calcutta', 'Bank of Bombay', 'Bank of Madras', 'Imperial Bank of India'],
    answer: 'Bank of Calcutta',
    explanation: 'Bank of Calcutta (1806) later became Bank of Bengal, then Imperial Bank of India, and finally SBI in 1955.',
  },
  {
    id: 48,
    topic: 'Geography',
    exam: 'SSC',
    question: 'Which is the world’s largest coral reef system?',
    options: ['Great Barrier Reef', 'Red Sea Coral Reef', 'Florida Reef', 'Mesoamerican Reef'],
    answer: 'Great Barrier Reef',
    explanation: 'The Great Barrier Reef off Australia is the world’s largest coral reef system.',
  },
  {
    id: 49,
    topic: 'Quantitative Aptitude',
    exam: 'SSC',
    question: 'What is the LCM of 4 and 6?',
    options: ['12', '24', '8', '18'],
    answer: '12',
    explanation: '12 is the smallest number divisible by both 4 and 6.',
  },

  // --- Banking ---
  {
    id: 50,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'Who is the current Governor of the Reserve Bank of India?',
    options: ['Sanjay Malhotra', 'Shaktikanta Das', 'Urjit Patel', 'Raghuram Rajan'],
    answer: 'Sanjay Malhotra',
    explanation: 'Sanjay Malhotra took over as the 26th RBI Governor in December 2024.',
  },
  {
    id: 51,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'As per RBI’s monetary policy in mid-2026, what is the current repo rate?',
    options: ['5.25%', '6.50%', '4.00%', '7.25%'],
    answer: '5.25%',
    explanation: 'The RBI kept the repo rate unchanged at 5.25% in its June 2026 MPC meeting.',
  },
  {
    id: 52,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'In which year was the Reserve Bank of India established?',
    options: ['1935', '1947', '1949', '1955'],
    answer: '1935',
    explanation: 'The RBI was established on 1 April 1935 under the RBI Act, 1934.',
  },
  {
    id: 53,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'Where is the headquarters of the Reserve Bank of India located?',
    options: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'],
    answer: 'Mumbai',
    explanation: 'RBI’s central office has been in Mumbai since 1937.',
  },
  {
    id: 54,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'State Bank of India traces its origins to the Bank of Calcutta, established in which year?',
    options: ['1806', '1770', '1865', '1921'],
    answer: '1806',
    explanation: 'Bank of Calcutta (1806) is the earliest predecessor of SBI.',
  },
  {
    id: 55,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does NEFT stand for?',
    options: [
      'National Electronic Funds Transfer',
      'National Electronic Fund Transaction',
      'Net Electronic Funds Transfer',
      'National Economic Funds Transfer',
    ],
    answer: 'National Electronic Funds Transfer',
    explanation: 'NEFT is a nationwide electronic funds transfer system in India.',
  },
  {
    id: 56,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does IFSC stand for?',
    options: [
      'Indian Financial System Code',
      'Indian Fund Settlement Code',
      'International Financial System Code',
      'Indian Financial Security Code',
    ],
    answer: 'Indian Financial System Code',
    explanation: 'IFSC uniquely identifies a bank branch for electronic transfers.',
  },
  {
    id: 57,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'Which is India’s largest public sector bank by assets?',
    options: ['State Bank of India', 'Punjab National Bank', 'Bank of Baroda', 'Canara Bank'],
    answer: 'State Bank of India',
    explanation: 'SBI is India’s largest bank by assets and branch network.',
  },
  {
    id: 58,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does CRR stand for in banking?',
    options: ['Cash Reserve Ratio', 'Credit Reserve Ratio', 'Capital Reserve Ratio', 'Cash Return Ratio'],
    answer: 'Cash Reserve Ratio',
    explanation: 'CRR is the minimum percentage of deposits banks must hold with the RBI.',
  },
  {
    id: 59,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does SLR stand for?',
    options: ['Statutory Liquidity Ratio', 'Statutory Loan Ratio', 'Standard Liquidity Ratio', 'Secured Lending Ratio'],
    answer: 'Statutory Liquidity Ratio',
    explanation: 'SLR is the minimum percentage of deposits banks must maintain in liquid assets.',
  },
  {
    id: 60,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does NPA stand for in banking terminology?',
    options: ['Non-Performing Asset', 'Net Profit Account', 'Non-Payable Amount', 'Net Performing Asset'],
    answer: 'Non-Performing Asset',
    explanation: 'An NPA is a loan on which the borrower has stopped making interest or principal payments.',
  },
  {
    id: 61,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'Which committee recommended major banking sector reforms in India in 1991?',
    options: ['Narasimham Committee', 'Chakravarty Committee', 'Tarapore Committee', 'Rangarajan Committee'],
    answer: 'Narasimham Committee',
    explanation: 'The Narasimham Committee (1991) recommended sweeping banking sector reforms.',
  },
  {
    id: 62,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does UPI stand for?',
    options: ['Unified Payments Interface', 'United Payments Interface', 'Universal Payment Index', 'Unified Payment Index'],
    answer: 'Unified Payments Interface',
    explanation: 'UPI, built by NPCI, enables instant inter-bank transactions via mobile.',
  },
  {
    id: 63,
    topic: 'Quantitative Aptitude',
    exam: 'Banking',
    question: 'What is the simple interest on Rs. 1000 at 5% per annum for 2 years?',
    options: ['Rs. 100', 'Rs. 50', 'Rs. 150', 'Rs. 200'],
    answer: 'Rs. 100',
    explanation: 'SI = (P x R x T)/100 = (1000 x 5 x 2)/100 = Rs. 100.',
  },
  {
    id: 64,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'Which body regulates the insurance sector in India?',
    options: ['IRDAI', 'SEBI', 'RBI', 'NABARD'],
    answer: 'IRDAI',
    explanation: 'The Insurance Regulatory and Development Authority of India regulates insurers.',
  },
  {
    id: 65,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What is the full form of SEBI?',
    options: [
      'Securities and Exchange Board of India',
      'Securities and Exchange Bureau of India',
      'State Exchange Board of India',
      'Savings and Exchange Board of India',
    ],
    answer: 'Securities and Exchange Board of India',
    explanation: 'SEBI regulates India’s securities and capital markets.',
  },
  {
    id: 66,
    topic: 'Banking Awareness',
    exam: 'Banking',
    question: 'What does NABARD stand for?',
    options: [
      'National Bank for Agriculture and Rural Development',
      'National Board for Agricultural Refinance and Development',
      'National Agency for Rural Banking and Development',
      'National Bank for Agricultural Research and Development',
    ],
    answer: 'National Bank for Agriculture and Rural Development',
    explanation: 'NABARD is the apex development bank for agriculture and rural credit in India.',
  },

  // --- Railway ---
  {
    id: 67,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'In which year did the first passenger train run in India?',
    options: ['1853', '1857', '1830', '1870'],
    answer: '1853',
    explanation: 'India’s first passenger train ran on 16 April 1853.',
  },
  {
    id: 68,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'The first passenger train in India ran between Bori Bunder (Mumbai) and which city?',
    options: ['Thane', 'Pune', 'Surat', 'Nashik'],
    answer: 'Thane',
    explanation: 'The 34 km journey connected Bori Bunder to Thane.',
  },
  {
    id: 69,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'India has the ____ largest railway network in the world by track length.',
    options: ['Fourth', 'Second', 'Third', 'Fifth'],
    answer: 'Fourth',
    explanation: 'India ranks fourth after the US, China, and Russia in railway network length.',
  },
  {
    id: 70,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'Where is the headquarters of Indian Railways located?',
    options: ['New Delhi', 'Mumbai', 'Kolkata', 'Chennai'],
    answer: 'New Delhi',
    explanation: 'Indian Railways is headquartered at Rail Bhawan, New Delhi.',
  },
  {
    id: 71,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'Which railway station currently holds the record for the world’s longest railway platform?',
    options: ['Hubballi (Karnataka)', 'Gorakhpur (Uttar Pradesh)', 'Kharagpur (West Bengal)', 'Kollam (Kerala)'],
    answer: 'Hubballi (Karnataka)',
    explanation: 'Hubballi’s platform (1,507 m) overtook Gorakhpur’s record in 2023.',
  },
  {
    id: 72,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'Konkan Railway connects Maharashtra, Goa, and which other state?',
    options: ['Karnataka', 'Kerala', 'Gujarat', 'Andhra Pradesh'],
    answer: 'Karnataka',
    explanation: 'The Konkan Railway line runs through Maharashtra, Goa, and Karnataka.',
  },
  {
    id: 73,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'India’s first bullet train corridor (under construction) connects Mumbai and which city?',
    options: ['Ahmedabad', 'Surat', 'Pune', 'Nagpur'],
    answer: 'Ahmedabad',
    explanation: 'The Mumbai-Ahmedabad High Speed Rail corridor is India’s first bullet train project.',
  },
  {
    id: 74,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'Vande Bharat Express is classified as a ____ train.',
    options: ['Semi-high speed', 'Diesel-electric', 'Metro', 'Freight'],
    answer: 'Semi-high speed',
    explanation: 'Vande Bharat is India’s indigenously built semi-high speed train.',
  },
  {
    id: 75,
    topic: 'General Science',
    exam: 'Railway',
    question: 'What is the SI unit of speed?',
    options: ['Metre per second', 'Kilometre per hour', 'Newton', 'Joule'],
    answer: 'Metre per second',
    explanation: 'Speed is measured in metres per second (m/s) in the SI system.',
  },
  {
    id: 76,
    topic: 'General Science',
    exam: 'Railway',
    question: 'Which gas is essential for respiration in humans?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    answer: 'Oxygen',
    explanation: 'Oxygen is required for cellular respiration in humans.',
  },
  {
    id: 77,
    topic: 'General Science',
    exam: 'Railway',
    question: 'Newton’s First Law of Motion is also known as the Law of?',
    options: ['Inertia', 'Gravitation', 'Momentum', 'Energy Conservation'],
    answer: 'Inertia',
    explanation: 'Newton’s First Law describes the property of inertia in objects.',
  },
  {
    id: 78,
    topic: 'General Science',
    exam: 'Railway',
    question: 'What is the freezing point of water at sea level?',
    options: ['0°C', '100°C', '-10°C', '32°C'],
    answer: '0°C',
    explanation: 'Water freezes at 0°C at standard atmospheric pressure.',
  },
  {
    id: 79,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'Which Indian Railway zone is headquartered in Kolkata?',
    options: ['Eastern Railway', 'Southern Railway', 'Western Railway', 'Central Railway'],
    answer: 'Eastern Railway',
    explanation: 'Eastern Railway, one of the oldest zones, is headquartered in Kolkata.',
  },
  {
    id: 80,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'What does RRB stand for in the context of railway recruitment?',
    options: ['Railway Recruitment Board', 'Railway Regional Board', 'Railway Regulatory Board', 'Rail Roads Board'],
    answer: 'Railway Recruitment Board',
    explanation: 'RRBs conduct recruitment exams for Indian Railways posts.',
  },
  {
    id: 81,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'What is the full form of IRCTC?',
    options: [
      'Indian Railway Catering and Tourism Corporation',
      'Indian Railway Cargo and Transport Corporation',
      'Indian Rail Coach and Ticketing Corporation',
      'Indian Railway Construction and Tourism Corporation',
    ],
    answer: 'Indian Railway Catering and Tourism Corporation',
    explanation: 'IRCTC handles ticketing, catering, and tourism services for Indian Railways.',
  },
  {
    id: 82,
    topic: 'General Science',
    exam: 'Railway',
    question: 'Which acid is present in lemon?',
    options: ['Citric acid', 'Acetic acid', 'Ascorbic acid', 'Oxalic acid'],
    answer: 'Citric acid',
    explanation: 'Citric acid gives lemons their sour taste.',
  },
  {
    id: 83,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'The Railway Budget was merged with the Union Budget of India starting from which year?',
    options: ['2017', '2014', '2019', '2020'],
    answer: '2017',
    explanation: 'The separate Railway Budget was merged into the Union Budget from 2017 onward.',
  },
  {
    id: 84,
    topic: 'Railway GK',
    exam: 'Railway',
    question: 'Which was the first metro railway system in India?',
    options: ['Kolkata Metro', 'Delhi Metro', 'Mumbai Metro', 'Chennai Metro'],
    answer: 'Kolkata Metro',
    explanation: 'Kolkata Metro, opened in 1984, was India’s first metro railway.',
  },
]

export const mockTests = [
  {
    id: 1,
    title: 'JEE Mock Sprint',
    duration: '30 min',
    questions: 25,
    level: 'Intermediate',
  },
  {
    id: 2,
    title: 'UPSC General Studies',
    duration: '45 min',
    questions: 40,
    level: 'Advanced',
  },
]

export const adminStats = [
  { label: 'Active Students', value: '1840' },
  { label: 'Questions Managed', value: '12850' },
  { label: 'Mock Tests', value: '96' },
]
